apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: whhthh4kd-nodejs
  janus-idp.io/tekton: whhthh4kd-nodejs
  backstage.io/kubernetes-id: whhthh4kd-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: whhthh4kd-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
